name: 米游社原神每日签到

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who are you?'
        required: true
        default: ''
  repository_dispatch:
  schedule:
    - cron: "0 0 * * *" # cron表达式，Actions时区是UTC+8时间，所以要往前推8个小时

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16.3.0'
      
      - name: Run sign
        env:
          SIGN_TARGET_COOKIE_YUU: ${{ secrets.YUU_COOKIE }}
        run: npm start

      - name: Debug workflow_dispatch inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"
      
      - name: Debug repository_dispatch trigger
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "event_name: ${{ github.event_name }}"
          echo "event action: ${{ github.event.action }}"
          echo "'foo' field: ${{ github.event.client_payload.foo }}"
          echo "payload: ${{ toJson(github.event.client_payload) }}"